name-template: 'v$NEXT_PATCH_VERSION Example title'
tag-template: 'v$NEXT_PATCH_VERSION'
exclude-labels:
  - 'skip-changelog'
categories:
  - title: 'New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  ## What’s Changed

  $CHANGES
  
